name: Create automatic pull request

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Pull Request Action
        uses: repo-sync/pull-request@v2.6
        with:
          source_branch: specification/feature-files
          destination_branch: main
          pr_title: Merge specification/feature-files into main
          pr_body: An automated PR to update changes made to feature files into the main branch.
          pr_label: auto-pr
          pr_reviewer: AutioL25187-pki
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
