name: Create automatic pull request

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Pull Request Action
        uses: repo-sync/pull-request@v2.6
        with:
          source_branch: specification/feature-files
          destination_branch: main
          pr_title: Pulrikuestin otsikko
          pr_body: ":crown: *An automated PR*"
          pr_label: auto-pr
          pr_reviewer: AutioL25187-pki
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
