name: Auto merge main into specification/feature-files

on:
  workflow_dispatch:
  # TODO: cron schedule daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        id: create-pr
        uses: repo-sync/pull-request@v2.6
        with:
          source_branch: main
          destination_branch: specification/feature-files
          pr_title: Merge main into specification/feature-files
          pr_body: An automated PR to merge the main branch into the specification/feature-files branch.
          pr_label: auto-pr
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Merge Pull Request
        if: ${{ steps.create-pr.outputs.pr_number }}
        uses: sudo-bot/action-pull-request-merge@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.create-pr.outputs.pr_number }}
          merge-method: merge
          merge-title: Merged main into specification/feature-files #${{steps.create-pr.outputs.pr_number}}
          merge-message: This is an automatic merge done by $GITHUB_WORKFLOW workflow.
