name: Create automatic pull request

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        id: create-pr
        uses: repo-sync/pull-request@v2.6
        with:
          source_branch: specification/feature-files
          destination_branch: main
          pr_title: Merge specification/feature-files into main
          pr_body: An automated PR to update changes made to feature files into the main branch.
          pr_label: auto-pr
          pr_allow_empty: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request v2
        uses: sudo-bot/action-pull-request-merge@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{steps.create-pr.outputs.pr_number}}
          merge-method: merge
          filter-label: auto-pr
          merge-title: "Merged specification into main #${{steps.create-pr.outputs.pr_number}}"
          merge-message: "MERGED specification into main #${{steps.create-pr.outputs.pr_number}}"
