name: Cron test

# Controls when the workflow will run
on:
  schedule:
  - cron: 1/3 * * * *
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello, world!
        run: echo Hello, world!
        
