name: Cron test

on:
  schedule:
  - cron: 4/6 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello, world!
        run: echo Hello, $GITHUB_EVENT_NAME!
        
