name: Cron test

on:
  #schedule:
  #- cron: '*/10 * * * *'
  push:
    paths: trigger/*
    branches: feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello, world!
        run: echo Hello, $GITHUB_EVENT_NAME!
        
      - name: Current branch
        run: echo Current branch is $GITHUB_REF
